// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'document_sale_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$DocumentSaleModelImpl _$$DocumentSaleModelImplFromJson(
        Map<String, dynamic> json) =>
    _$DocumentSaleModelImpl(
      saleHdId: json['sale_hd_id'] as String?,
      companyId: json['master_company_id'] as String?,
      branchId: json['master_branch_id'] as String?,
      branchCode: json['master_branch_code'] as String?,
      branchName: json['master_branch_name'] as String?,
      saleHdDocudate: json['sale_hd_docudate'] as String?,
      saleHdDocuno: json['sale_hd_docuno'] as String?,
      saleHdStatusId: json['sale_hd_status_id'] as num?,
      saleHdStatusName: json['sale_hd_status_name'] as String?,
      contactId: json['master_contact_id'] as String?,
      contactCode: json['master_contact_code'] as String?,
      contactName: json['master_contact_name'] as String?,
      contactDistrictId: json['master_contact_district_id'] as String?,
      contactPrefectureId: json['master_contact_prefecture_id'] as String?,
      contactProvinceId: json['master_contact_province_id'] as String?,
      contactPostcodeId: json['master_contact_postcode_id'] as String?,
      saleHdRemark: json['sale_hd_remark'] as String?,
      vatGroupId: json['master_vat_group_id'] as num?,
      saleHdTypeId: json['sale_hd_type_id'] as num?,
      saleHdCreditday: json['sale_hd_creditday'] as num?,
      whtCategoryId: json['wht_category_id'] as String?,
      saleHdAmount: json['sale_hd_amount'] as String?,
      saleHdTotalexcludeamnt: json['sale_hd_totalexcludeamnt'] as String?,
      saleHdTotalincludeamnt: json['sale_hd_totalincludeamnt'] as String?,
      saleHdBaseamnt: json['sale_hd_baseamnt'] as String?,
      saleHdVatamnt: json['sale_hd_vatamnt'] as String?,
      saleHdDiscountAmount: json['sale_hd_discount_amount'] as String?,
      saleHdWhtAmount: json['sale_hd_wht_amount'] as String?,
      saleHdNetamnt: json['sale_hd_netamnt'] as String?,
      saleHdCashAmount: json['sale_hd_cash_amount'] as String?,
      saleHdTransferAmount: json['sale_hd_transfer_amount'] as String?,
      saleHdCreditAmount: json['sale_hd_credit_amount'] as String?,
      saleHdChangeAmount: json['sale_hd_change_amount'] as String?,
      fullname: json['fullname'] as String?,
      saleHdCashReceived: json['sale_hd_cash_received'] as String?,
      saleHdRoundingAmount: json['sale_hd_rounding_amount'] as String?,
      whtCategoryName: json['wht_category_name'] as String?,
      whtCategoryRate: json['wht_category_rate'] as String?,
      vatGroupName: json['master_vat_group_name'] as String?,
      saleHdVatrate: json['sale_hd_vatrate'] as String?,
      saleHdVoucherAmount: json['sale_hd_voucher_amount'] as String?,
      contactAddress: json['master_contact_address'] as String?,
      contactTel: json['master_contact_tel'] as String?,
      contactTaxid: json['master_contact_taxid'] as String?,
      saleHdSavetime: json['sale_hd_savetime'] as String?,
      contactBranchname: json['master_contact_branchname'] as String?,
    );

Map<String, dynamic> _$$DocumentSaleModelImplToJson(
        _$DocumentSaleModelImpl instance) =>
    <String, dynamic>{
      'sale_hd_id': instance.saleHdId,
      'master_company_id': instance.companyId,
      'master_branch_id': instance.branchId,
      'master_branch_code': instance.branchCode,
      'master_branch_name': instance.branchName,
      'sale_hd_docudate': instance.saleHdDocudate,
      'sale_hd_docuno': instance.saleHdDocuno,
      'sale_hd_status_id': instance.saleHdStatusId,
      'sale_hd_status_name': instance.saleHdStatusName,
      'master_contact_id': instance.contactId,
      'master_contact_code': instance.contactCode,
      'master_contact_name': instance.contactName,
      'master_contact_district_id': instance.contactDistrictId,
      'master_contact_prefecture_id': instance.contactPrefectureId,
      'master_contact_province_id': instance.contactProvinceId,
      'master_contact_postcode_id': instance.contactPostcodeId,
      'sale_hd_remark': instance.saleHdRemark,
      'master_vat_group_id': instance.vatGroupId,
      'sale_hd_type_id': instance.saleHdTypeId,
      'sale_hd_creditday': instance.saleHdCreditday,
      'wht_category_id': instance.whtCategoryId,
      'sale_hd_amount': instance.saleHdAmount,
      'sale_hd_totalexcludeamnt': instance.saleHdTotalexcludeamnt,
      'sale_hd_totalincludeamnt': instance.saleHdTotalincludeamnt,
      'sale_hd_baseamnt': instance.saleHdBaseamnt,
      'sale_hd_vatamnt': instance.saleHdVatamnt,
      'sale_hd_discount_amount': instance.saleHdDiscountAmount,
      'sale_hd_wht_amount': instance.saleHdWhtAmount,
      'sale_hd_netamnt': instance.saleHdNetamnt,
      'sale_hd_cash_amount': instance.saleHdCashAmount,
      'sale_hd_transfer_amount': instance.saleHdTransferAmount,
      'sale_hd_credit_amount': instance.saleHdCreditAmount,
      'sale_hd_change_amount': instance.saleHdChangeAmount,
      'fullname': instance.fullname,
      'sale_hd_cash_received': instance.saleHdCashReceived,
      'sale_hd_rounding_amount': instance.saleHdRoundingAmount,
      'wht_category_name': instance.whtCategoryName,
      'wht_category_rate': instance.whtCategoryRate,
      'master_vat_group_name': instance.vatGroupName,
      'sale_hd_vatrate': instance.saleHdVatrate,
      'sale_hd_voucher_amount': instance.saleHdVoucherAmount,
      'master_contact_address': instance.contactAddress,
      'master_contact_tel': instance.contactTel,
      'master_contact_taxid': instance.contactTaxid,
      'sale_hd_savetime': instance.saleHdSavetime,
      'master_contact_branchname': instance.contactBranchname,
    };
