import 'package:freezed_annotation/freezed_annotation.dart';

import 'sale_dt_model.dart';
import 'sale_h_d_payment_type_model.dart';

part 'salehd_all_preview_model.freezed.dart';
part 'salehd_all_preview_model.g.dart';

@freezed
class SalehdAllPreviewModel with _$SalehdAllPreviewModel {
  const factory SalehdAllPreviewModel({
    @JsonKey(name: 'type_bill') String? typeBill,
    @JsonKey(name: 'type_bill_name') String? typeBillName,
    @JsonKey(name: 'salehd_id') String? salehdId,
    @JsonKey(name: 'salehd_docudate') String? salehdDocudate,
    @JsonKey(name: 'salehd_time') String? salehdTime,
    @JsonKey(name: 'salehd_docuno') String? salehdDocuno,
    @JsonKey(name: 'salehd_statusid') num? salehdStatusid,
    @JsonKey(name: 'salehd_empemployeemasterid') String? salehdEmpemployeemasterid,
    @JsonKey(name: 'salehd_arcustomerid') String? salehdArcustomerid,
    @JsonKey(name: 'salehd_arcustomer_name') String? salehdArcustomerName,
    @JsonKey(name: 'salehd_arcustomer_taxid') String? salehdArcustomerTaxid,
    @JsonKey(name: 'salehd_arcustomer_addr') String? salehdArcustomerAddr,
    @JsonKey(name: 'salehd_arcustomer_addr_district_id') String? salehdArcustomerAddrDistrictId,
    @JsonKey(name: 'salehd_arcustomer_addr_prefecture_id') String? salehdArcustomerAddrPrefectureId,
    @JsonKey(name: 'salehd_arcustomer_addr_province_id') String? salehdArcustomerAddrProvinceId,
    @JsonKey(name: 'salehd_arcustomer_addr_postcode_id') String? salehdArcustomerAddrPostcodeId,
    @JsonKey(name: 'salehd_remark') String? salehdRemark,
    @JsonKey(name: 'salehd_vatgroup_id') num? salehdVatgroupId,
    @JsonKey(name: 'salehd_vatrate') String? salehdVatrate,
    @JsonKey(name: 'salehd_totalexcludeamnt') String? salehdTotalexcludeamnt,
    @JsonKey(name: 'salehd_totalincludeamnt') String? salehdTotalincludeamnt,
    @JsonKey(name: 'salehd_totalincludeamnt_afterdepositamnt') String? salehdTotalincludeamntAfterdepositamnt,
    @JsonKey(name: 'salehd_baseamnt') String? salehdBaseamnt,
    @JsonKey(name: 'salehd_vatamnt') String? salehdVatamnt,
    @JsonKey(name: 'salehd_sumgoodamnt') String? salehdSumgoodamnt,
    @JsonKey(name: 'salehd_discountamnt') String? salehdDiscountamnt,
    @JsonKey(name: 'salehd_netamnt') String? salehdNetamnt,
    @JsonKey(name: 'salehd_cashamnt') String? salehdCashamnt,
    @JsonKey(name: 'salehd_transferamnt') String? salehdTransferamnt,
    @JsonKey(name: 'salehd_creditcardamnt') String? salehdCreditcardamnt,
    @JsonKey(name: 'salehd_depositamnt') String? salehdDepositamnt,
    @JsonKey(name: 'master_branch_id') String? branchId,
    @JsonKey(name: 'master_company_id') num? companyId,
    @JsonKey(name: 'salehd_discount_type_id') String? salehdDiscountTypeId,
    @JsonKey(name: 'salehd_cashamnt_actual') String? salehdCashamntActual,
    @JsonKey(name: 'salehd_changeamnt') String? salehdChangeamnt,
    @JsonKey(name: 'salehd_print_taxinvoice') bool? salehdPrintTaxinvoice,
    @JsonKey(name: 'salehd_voucheramnt') String? salehdVoucheramnt,
    @JsonKey(name: 'salehd_voucher_type_id') String? salehdVoucherTypeId,
    @JsonKey(name: 'salehd_point_quantity') String? salehdPointQuantity,
    @JsonKey(name: 'salehd_point_type_id') num? salehdPointTypeId,
    @JsonKey(name: 'salehd_point_redeem') String? salehdPointRedeem,
    @JsonKey(name: 'salehd_wht_category_id') String? salehdWhtCategoryId,
    @JsonKey(name: 'salehd_whtamnt') String? salehdWhtamnt,
    @JsonKey(name: 'salehd_arcustomer_redeemid') String? salehdArcustomerRedeemid,
    @JsonKey(name: 'salehd_arcustomer_redeemname') String? salehdArcustomerRedeemname,
    @JsonKey(name: 'salehd_tipamnt') String? salehdTipamnt,
    @JsonKey(name: 'salehd_table_name') String? salehdTableName,
    @JsonKey(name: 'salehd_feeamnt') String? salehdFeeamnt,
    @JsonKey(name: 'salehd_service_chargeamnt') String? salehdServiceChargeamnt,
    @JsonKey(name: 'salehd_print_taxinvoice_language') num? salehdPrintTaxinvoiceLanguage,
    @JsonKey(name: 'salehd_service_chargeamnt_takeaway') String? salehdServiceChargeamntTakeaway,
    @JsonKey(name: 'salehd_partneramnt') String? salehdPartneramnt,
    @JsonKey(name: 'salehd_discount_type_name') String? salehdDiscountTypeName,
    @JsonKey(name: 'promotion_point_type_name') String? promotionPointTypeName,
    @JsonKey(name: 'promotion_point_type_rate') String? promotionPointTypeRate,
    @JsonKey(name: 'wht_category_name') String? whtCategoryName,
    @JsonKey(name: 'salehd_arcustomer_redeemcode') String? salehdArcustomerRedeemcode,
    @JsonKey(name: 'master_vat_group_name') String? vatGroupName,
    @JsonKey(name: 'salehd_remark_order') String? salehdRemarkOrder,
    @JsonKey(name: 'salehd_empemployeemastercode') String? salehdEmpemployeemastercode,
    @JsonKey(name: 'emp_name') String? empName,
    @JsonKey(name: 'arcustomer_taxinvoice_name') String? arcustomerTaxinvoiceName,
    @JsonKey(name: 'arcustomer_taxinvoice_tel') String? arcustomerTaxinvoiceTel,
    @JsonKey(name: 'arcustomer_taxinvoice_taxid') String? arcustomerTaxinvoiceTaxid,
    @JsonKey(name: 'arcustomer_taxinvoice_addr') String? arcustomerTaxinvoiceAddr,
    @JsonKey(name: 'carry_forward_points') String? carryForwardPoints,
    @JsonKey(name: 'points_redeemed') String? pointsRedeemed,
    @JsonKey(name: 'points_earned') String? pointsEarned,
    @JsonKey(name: 'current_total_points') String? currentTotalPoints,
    @JsonKey(name: 'salehd_docudate_invoice') String? salehdDocudateInvoice,
    @JsonKey(name: 'point_quantity') String? pointQuantity,
    @JsonKey(name: 'sale_hd_discount') List<dynamic>? saleHdDiscount,
    @JsonKey(name: 'sale_dt') @Default([]) List<SaleDTModel> saleDt,
    @JsonKey(name: 'sale_hd_payment_type') @Default([]) List<SaleHDPaymentTypeModel> saleHdPaymentType,
  }) = _SalehdAllPreviewModel;

  factory SalehdAllPreviewModel.fromJson(Map<String, dynamic> json) => _$SalehdAllPreviewModelFromJson(json);
}
